codecov:
  branch: main
  require_ci_to_pass: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: no
  after_n_builds: 1
  show_carryforward_flags: true

github_checks:
  annotations: true

coverage:
  status:
    patch:
      default:
        target: 69%
        threshold: 5%
        base: auto
        only_pulls: true
        flags:
          - unit-tests
    project:
      default:
        target: auto
        threshold: 1%
      theia-unit-tests:
        target: auto
        threshold: 1%
        flags:
          - unit-tests
      theia-kind-e2e-tests:
        target: 60%
        threshold: 1%
        flags:
          - kind-e2e-tests
      python-unit-tests:
        target: 50%
        threshold: 1%
        flags:
          - python-coverage

flag_management:
  default_rules:
    carryforward: true
ignore:
  - "**/testing/*.go"
  - "**/mock_*.go"
  - "**/*generate*.go"
  - "pkg/client"
  - "**/pkg/client"
  - "third_party"
  - "pkg/api"
  - "snowflake"
